#index:
#    path: /
#    controller: App\Controller\DefaultController::index
gregwar_captcha_routing:
  resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"

homepage:
  path:       /
  controller: App\Controller\AccueilController::index